### ISSUE TITLE
publish all languages to NPM

### ISSUE THREAD

**Issue by maerten** [bramstein/hyphenation-patterns#1]
npm ERR! 404 'hyphenation.nl-nl' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 

Thanks!

**Comment by bramstein** [comment]
The Dutch pattern files are called `hyphenation.nl`. I just published them to npm. I haven't published any other pattern files as I didn't really want to spam the npm repository. Perhaps I should reconsider.

**Comment by maerten** [comment]
Thanks! Just publish them, that's what the repository is for!
