### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Scopestyle** [bramstein/hyphenation-patterns#5]
Hi, I have an issue with the jQuery implenetation of  de.js file, when implemented I receive the following error:

"ReferenceError: module is not defined" on "module.exports = {"

What can I do to fix this?

**Comment by bramstein** [comment]
I think the problem should go away if you use the [de.js](https://github.com/bramstein/hyphenation-patterns/blob/master/dist/browser/de.js) from the `dist/browser` directory. The ones from the `src` directory are not compatible with the jQuery version of Hypher.
