### ISSUE TITLE
patterns conversion from TeX?

### ISSUE THREAD

**Issue by eroux** [bramstein/hyphenation-patterns#9]
I'm wondering how the different js patterns are produced? I'd like to publish a website doing hyphenation for [new Latin patterns](https://github.com/gregorio-project/hyphen-la), but I don't know how to generate a new `la.js`... Any clue?

**Comment by bramstein** [comment]
Hypher uses the same pattern files as Hyphenator.js. I think those pattern files are converted by a script that joins based on the length of the pattern.

**Comment by eroux** [comment]
Thanks, I've got a pointer to a wiki page on https://github.com/mnater/Hyphenator/issues/256, but it's not detailed enough to actually implement anything... Would you happen to know where such a script could be?

**Comment by bramstein** [comment]
I think it uses this script: http://tug.org/svn/texhyphen/trunk/collaboration/source/hyphenator/generate-js-Hyphenator.rb?view=markup

I haven't looked at it in a long time, so I don't know if it still generates correct output. Might be a good place to start though.

**Comment by eroux** [comment]
Thanks a lot! It doesn't seem to output something in line with the documentation, so it might just be outdated... But I've finally found http://mnater.github.io/Hyphenator/compressor.html which does the conversion. A script would have been better, but that's better than nothing! Thanks for your help

**Comment by bramstein** [comment]
Ah nice. Glad you found it.

@mnater we should wrap that up as a Node.js module and make it an executable.

**Comment by eroux** [comment]
That would be very nice indeed!

**Comment by mnater** [comment]
Agreed! It's on my todo-list.
I'm working on patgen for node.js
It will be part of that package. I plan to release it this summer (too much other projects:-(

**Comment by eroux** [comment]
That's good to know, thanks a lot!
